/* Auto-generated by genmsg_cpp for file /home/dellux09/ros_workspace/pa10control/msg/pa10Command.msg */
#ifndef PA10CONTROL_MESSAGE_PA10COMMAND_H
#define PA10CONTROL_MESSAGE_PA10COMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace pa10control
{
template <class ContainerAllocator>
struct pa10Command_ {
  typedef pa10Command_<ContainerAllocator> Type;

  pa10Command_()
  : header()
  , joint(0)
  , type(false)
  , Duration()
  , value(0.0)
  , enable(false)
  , brake(false)
  {
  }

  pa10Command_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , joint(0)
  , type(false)
  , Duration()
  , value(0.0)
  , enable(false)
  , brake(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _joint_type;
  uint8_t joint;

  typedef uint8_t _type_type;
  uint8_t type;

  typedef ros::Duration _Duration_type;
  ros::Duration Duration;

  typedef double _value_type;
  double value;

  typedef uint8_t _enable_type;
  uint8_t enable;

  typedef uint8_t _brake_type;
  uint8_t brake;


private:
  static const char* __s_getDataType_() { return "pa10control/pa10Command"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0ec791b71599e47d9c5545b896b597cb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
uint8 joint\n\
bool type #0 torque, 1 velocity\n\
duration Duration\n\
float64 value\n\
bool enable\n\
bool brake\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, joint);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, Duration);
    ros::serialization::serialize(stream, value);
    ros::serialization::serialize(stream, enable);
    ros::serialization::serialize(stream, brake);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, joint);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, Duration);
    ros::serialization::deserialize(stream, value);
    ros::serialization::deserialize(stream, enable);
    ros::serialization::deserialize(stream, brake);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(joint);
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(Duration);
    size += ros::serialization::serializationLength(value);
    size += ros::serialization::serializationLength(enable);
    size += ros::serialization::serializationLength(brake);
    return size;
  }

  typedef boost::shared_ptr< ::pa10control::pa10Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa10control::pa10Command_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pa10Command
typedef  ::pa10control::pa10Command_<std::allocator<void> > pa10Command;

typedef boost::shared_ptr< ::pa10control::pa10Command> pa10CommandPtr;
typedef boost::shared_ptr< ::pa10control::pa10Command const> pa10CommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pa10control::pa10Command_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pa10control::pa10Command_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pa10control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pa10control::pa10Command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pa10control::pa10Command_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pa10control::pa10Command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0ec791b71599e47d9c5545b896b597cb";
  }

  static const char* value(const  ::pa10control::pa10Command_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0ec791b71599e47dULL;
  static const uint64_t static_value2 = 0x9c5545b896b597cbULL;
};

template<class ContainerAllocator>
struct DataType< ::pa10control::pa10Command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pa10control/pa10Command";
  }

  static const char* value(const  ::pa10control::pa10Command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pa10control::pa10Command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint8 joint\n\
bool type #0 torque, 1 velocity\n\
duration Duration\n\
float64 value\n\
bool enable\n\
bool brake\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::pa10control::pa10Command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::pa10control::pa10Command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::pa10control::pa10Command_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pa10control::pa10Command_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.joint);
    stream.next(m.type);
    stream.next(m.Duration);
    stream.next(m.value);
    stream.next(m.enable);
    stream.next(m.brake);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pa10Command_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa10control::pa10Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pa10control::pa10Command_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "Duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.Duration);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PA10CONTROL_MESSAGE_PA10COMMAND_H

