/* Auto-generated by genmsg_cpp for file /home/dellux09/ros_workspace/pa10control/msg/pa10Geometry.msg */
#ifndef PA10CONTROL_MESSAGE_PA10GEOMETRY_H
#define PA10CONTROL_MESSAGE_PA10GEOMETRY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace pa10control
{
template <class ContainerAllocator>
struct pa10Geometry_ {
  typedef pa10Geometry_<ContainerAllocator> Type;

  pa10Geometry_()
  : header()
  , w1(0.0)
  , w2(0.0)
  , w3(0.0)
  , w4(0.0)
  , w5(0.0)
  , w6(0.0)
  , w7(0.0)
  {
  }

  pa10Geometry_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , w1(0.0)
  , w2(0.0)
  , w3(0.0)
  , w4(0.0)
  , w5(0.0)
  , w6(0.0)
  , w7(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _w1_type;
  double w1;

  typedef double _w2_type;
  double w2;

  typedef double _w3_type;
  double w3;

  typedef double _w4_type;
  double w4;

  typedef double _w5_type;
  double w5;

  typedef double _w6_type;
  double w6;

  typedef double _w7_type;
  double w7;


private:
  static const char* __s_getDataType_() { return "pa10control/pa10Geometry"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ee7b88b7b4160ca784e30f59ae34469b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64 w1\n\
float64 w2\n\
float64 w3\n\
float64 w4\n\
float64 w5\n\
float64 w6\n\
float64 w7\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, w1);
    ros::serialization::serialize(stream, w2);
    ros::serialization::serialize(stream, w3);
    ros::serialization::serialize(stream, w4);
    ros::serialization::serialize(stream, w5);
    ros::serialization::serialize(stream, w6);
    ros::serialization::serialize(stream, w7);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, w1);
    ros::serialization::deserialize(stream, w2);
    ros::serialization::deserialize(stream, w3);
    ros::serialization::deserialize(stream, w4);
    ros::serialization::deserialize(stream, w5);
    ros::serialization::deserialize(stream, w6);
    ros::serialization::deserialize(stream, w7);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(w1);
    size += ros::serialization::serializationLength(w2);
    size += ros::serialization::serializationLength(w3);
    size += ros::serialization::serializationLength(w4);
    size += ros::serialization::serializationLength(w5);
    size += ros::serialization::serializationLength(w6);
    size += ros::serialization::serializationLength(w7);
    return size;
  }

  typedef boost::shared_ptr< ::pa10control::pa10Geometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa10control::pa10Geometry_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pa10Geometry
typedef  ::pa10control::pa10Geometry_<std::allocator<void> > pa10Geometry;

typedef boost::shared_ptr< ::pa10control::pa10Geometry> pa10GeometryPtr;
typedef boost::shared_ptr< ::pa10control::pa10Geometry const> pa10GeometryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pa10control::pa10Geometry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pa10control::pa10Geometry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pa10control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pa10control::pa10Geometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pa10control::pa10Geometry_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pa10control::pa10Geometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee7b88b7b4160ca784e30f59ae34469b";
  }

  static const char* value(const  ::pa10control::pa10Geometry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xee7b88b7b4160ca7ULL;
  static const uint64_t static_value2 = 0x84e30f59ae34469bULL;
};

template<class ContainerAllocator>
struct DataType< ::pa10control::pa10Geometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pa10control/pa10Geometry";
  }

  static const char* value(const  ::pa10control::pa10Geometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pa10control::pa10Geometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 w1\n\
float64 w2\n\
float64 w3\n\
float64 w4\n\
float64 w5\n\
float64 w6\n\
float64 w7\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::pa10control::pa10Geometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::pa10control::pa10Geometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::pa10control::pa10Geometry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pa10control::pa10Geometry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.w1);
    stream.next(m.w2);
    stream.next(m.w3);
    stream.next(m.w4);
    stream.next(m.w5);
    stream.next(m.w6);
    stream.next(m.w7);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pa10Geometry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa10control::pa10Geometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pa10control::pa10Geometry_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "w1: ";
    Printer<double>::stream(s, indent + "  ", v.w1);
    s << indent << "w2: ";
    Printer<double>::stream(s, indent + "  ", v.w2);
    s << indent << "w3: ";
    Printer<double>::stream(s, indent + "  ", v.w3);
    s << indent << "w4: ";
    Printer<double>::stream(s, indent + "  ", v.w4);
    s << indent << "w5: ";
    Printer<double>::stream(s, indent + "  ", v.w5);
    s << indent << "w6: ";
    Printer<double>::stream(s, indent + "  ", v.w6);
    s << indent << "w7: ";
    Printer<double>::stream(s, indent + "  ", v.w7);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PA10CONTROL_MESSAGE_PA10GEOMETRY_H

